{% set version = "1.44.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-reticulate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/reticulate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/reticulate/reticulate_{{ version }}.tar.gz
  sha256: 2e714a832a5d7c48c539f1725850e04419565a4437caaa627435f5cc4c161382
  patches:
    - patches/0001-include-signal.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpptoml                   # [build_platform != target_platform]
    - r-jsonlite                   # [build_platform != target_platform]
    - r-png                        # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=1.0.7
    - r-rcpptoml
    - r-here
    - r-jsonlite
    - r-png
    - r-rappdirs
    - r-rlang
    - r-withr
  run:
    - r-base
    - r-matrix
    - r-rcpp >=1.0.7
    - r-rcpptoml
    - r-here
    - r-jsonlite
    - r-png
    - r-rappdirs
    - r-rlang
    - r-withr

test:
  commands:
    - $R -e "library('reticulate')"           # [not win]
    - "\"%R%\" -e \"library('reticulate')\""  # [win]

about:
  home: https://github.com/rstudio/reticulate
  doc_url: https://rstudio.github.io/reticulate/
  license: Apache-2.0
  summary: Interface to 'Python' modules, classes, and functions. When calling into 'Python', R data types are automatically converted to their equivalent 'Python' types. When values are returned from 'Python' to R they are converted back to R types. Compatible with all versions of 'Python' >= 2.7.
  license_family: APACHE
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
