{% set version = '1.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reticulate
  version: {{ version|replace("-", "_") }}

source:
  fn: reticulate_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/reticulate_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/reticulate/reticulate_{{ version }}.tar.gz
  sha256: 15a5d1de30427e421be9fda1fe50b3e42d529ba57f5d1aaf8c73f6ed3a8fd20c

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcpp >=0.12.7
    - r-jsonlite
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp >=0.12.7
    - r-jsonlite
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('reticulate')"  # [not win]
    - "\"%R%\" -e \"library('reticulate')\""  # [win]

about:
  home: https://github.com/rstudio/reticulate
  license: Apache 2.0
  summary: Interface to 'Python' modules, classes, and functions. When calling into 'Python',
    R data types are automatically converted to their equivalent 'Python' types. When
    values are returned from 'Python' to R they are converted back to R types. Compatible
    with all versions of 'Python' >= 2.7.
  license_family: APACHE

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
