{% set version = "1.21" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reticulate
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/reticulate_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/reticulate/reticulate_{{ version }}.tar.gz
  sha256: b4553173d55f624462eb30b51f054d6a39f4e77c6d23014a6611b6ebc0284bcb

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-jsonlite                 # [build_platform != target_platform]
    - r-png                      # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.12.7
    - r-jsonlite
    - r-png
    - r-rappdirs
    - r-withr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.12.7
    - r-jsonlite
    - r-png
    - r-rappdirs
    - r-withr

test:
  commands:
    - $R -e "library('reticulate')"           # [not win]
    - "\"%R%\" -e \"library('reticulate')\""  # [win]

about:
  home: https://github.com/rstudio/reticulate
  license: Apache-2.0
  summary: Interface to 'Python' modules, classes, and functions. When calling into 'Python', R data types are automatically converted to their equivalent 'Python' types. When values are returned from 'Python' to R they are converted back to R types. Compatible with all versions of 'Python' >= 2.7.
  license_family: APACHE
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: reticulate
# Type: Package
# Title: Interface to 'Python'
# Version: 1.14
# Authors@R: c( person("Kevin", "Ushey", role = c("aut", "cre"), email = "kevin@rstudio.com"), person("JJ", "Allaire", role = c("aut"), email = "jj@rstudio.com"), person("RStudio", role = c("cph", "fnd")), person("Yuan", "Tang", role = c("aut", "cph"), email = "terrytangyuan@gmail.com", comment = c(ORCID = "0000-0001-5243-233X")), person("Dirk", "Eddelbuettel", role = c("ctb", "cph"), email = "edd@debian.org"), person("Bryan", "Lewis", role = c("ctb", "cph"), email = "blewis@illposed.net"), person("Ryan", "Hafen", role = c("ctb", "cph"), email = "rhafen@gmail.com"), person("Marcus", "Geelnard", role = c("ctb", "cph"), comment = "TinyThread library, http://tinythreadpp.bitsnbites.eu/") )
# Description: Interface to 'Python' modules, classes, and functions. When calling into 'Python', R data types are automatically converted to their equivalent 'Python' types. When values are returned from 'Python' to R they are converted back to R types. Compatible with all versions of 'Python' >= 2.7.
# License: Apache License 2.0
# URL: https://github.com/rstudio/reticulate
# BugReports: https://github.com/rstudio/reticulate/issues
# SystemRequirements: Python (>= 2.7.0)
# Encoding: UTF-8
# LazyData: true
# Depends: R (>= 3.0)
# Imports: graphics, jsonlite, Matrix, methods, rappdirs, Rcpp (>= 0.12.7), utils
# Suggests: callr, knitr, rmarkdown, testthat
# LinkingTo: Rcpp
# RoxygenNote: 7.0.2
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-12-16 21:35:53 UTC; kevinushey
# Author: Kevin Ushey [aut, cre], JJ Allaire [aut], RStudio [cph, fnd], Yuan Tang [aut, cph] (<https://orcid.org/0000-0001-5243-233X>), Dirk Eddelbuettel [ctb, cph], Bryan Lewis [ctb, cph], Ryan Hafen [ctb, cph], Marcus Geelnard [ctb, cph] (TinyThread library, http://tinythreadpp.bitsnbites.eu/)
# Maintainer: Kevin Ushey <kevin@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-12-17 13:40:02 UTC
