appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: zsDfOkOw6hT6R8MmZFQWWmypga6iewdP4bTa/UCzjAQN69pJFvS4MbNTuwGWAbd2P09iyGo04VD+8I+tqnEkPwE+cEqQL7yrChkiTGnb7QPg1YJTWVpJMCbd1ejrEdKRO5PFHLeQKHOQqyoeSYHLfY7NFOF02iDYx7BV5b51ttnuKOgtUxGfXVs+8cmc7CQ68nB3bLwjF09ZsOFBIKBQtPDE+yVZJCfVboyYVCQcWO/ObwsL4pVBJUHwH4eBhmN1r4PHs5Q+2KaE0Vpgw92dWaigX+utaXe2SRERSFyC0sAQnzeD/377MdIX26RO6/rlD7jixlz/WpfYnoT8UA8qgE+lGT2VKBaRADtwHagpJyguvfR0/E/QucjMuW+xanEr4L7C9vZax79Pq53c31WbypQb6O6yglMY+p/2C1xW61gPIeoEMmbBD+DETE9uKbqAWLiZtGfdSXQiMdiOioe/qG0OwwMMoPg6FJBJhNp/XElO7oLS6zKj6fCDaS5YK+Jy9EPSZ0wSzPj9KFt9pmZlLY32VjZWxTkfqAuIc8iu/MAXjtTpF3oSpnsW7FZcGQRX9DBbhIZpoDnQ2iEPsIb64B3kO2eDUnRZKAPMrwEl0zQqJRLX8fhFg6SJnLH6I0q6IgcY4z2nxLplJuE+cBNyxDMsqqzoqS5czqWPi4NfECk=
conda_forge_output_validation: true
